image: langdb/ai-gateway:latest
replicaCount: 1
env:
  CLICKHOUSE_HOST: clickhouse
  REDIS_HOST: redis
  POSTGRES_HOST: postgres
  POSTGRES_USER: langdb
  POSTGRES_PASSWORD: langdb
  POSTGRES_DB: langdb
config: |
  # Refer to ai-gateway.yaml documentation for more details
  http:
    host: "0.0.0.0"
    port: 8080
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
